### ISSUE TITLE
Object storage tests fail if region is not default region

### ISSUE THREAD

**Issue by Mia-Cross** [scaleway/terraform-provider-scaleway#2255]
During the processing of issue #1934, it was noticed that most object storage tests fail if the region of the bucket is different from the default region of the client. The tests should be refactored and fixed resource by resource.
Also these PRs should fix the failing nightly tests.

- [x] Object: #2277 
- [x] Object bucket: #2256 
- [x] Object bucket ACL: #2261 
- [x] Object bucket lock configuration: #2271 
- [x] Object bucket policy : #2229 
- [x] Object bucket website configuration: #2263 
- [x] Finalization (replace all old function with the new ones): #2278
