### ISSUE TITLE
v2.0.0 Roadmap

### ISSUE THREAD

**Issue by remyleone** [scaleway/terraform-provider-scaleway#576]
- [X] [Migrate to Terraform SDKv2](https://www.terraform.io/docs/extend/guides/v2-upgrade-guide.html) (https://github.com/scaleway/terraform-provider-scaleway/pull/575) 
- [x] Remove beta from the resource name (ex: `scaleway_k8s_cluster_beta`-> `scaleway_k8s_cluster`) (#669)
- [X] Ensure that https://github.com/scaleway/scaleway-sdk-go is the only Scaleway SDK used (https://github.com/scaleway/terraform-provider-scaleway/pull/578)
- [x] Remove deprecated provider schema fields
- [x] Remove deprecated configuration file and environment variables
- [x] Remove deprecated resources (mainly for the instance product) (ex: `resource_volume`, `resource_server`, ...) (https://github.com/scaleway/terraform-provider-scaleway/pull/578)
- [x] Change the configuration precedence
- [x] Ensure that acceptance CI does not leak credentials
- [ ] Add a sentry configuration in case the provider crash (#697)

**Comment by jdiaz-fa** [comment]
Is this new version going to allow first protocol - load balancing ?

**Comment by remyleone** [comment]
@jdiaz-fa It will: https://github.com/scaleway/terraform-provider-scaleway/pull/698

**Comment by remyleone** [comment]
I'm very happy to announce that the first release candidate of the v2 of terraform is released :tada: 
This version includes new features (project id in resources, vpc, ...), massive refactoring, and more testing. To have a view of the changelog for this release go take a look here on the [release page](https://github.com/scaleway/terraform-provider-scaleway/releases/tag/v2.0.0-rc1).
In particular, some of those changes are breaking changes, we wrote [a guide](https://registry.terraform.io/providers/scaleway/scaleway/latest/docs/guides/migration_guide_v2) to help you migrate as quickly as possible to the new version.

You can view this guide live on the terraform [registry](https://registry.terraform.io/providers/scaleway/scaleway/latest).
